List<String> presidentimages = [
  'morzbakh.jpg',
  'Heidar.jpg',
  'aborgela.jpg',
  'hassan.jpg',
  'helmy.jpg',
  'darweesh.jpg'
];
List<String> presidentnames = [
  'Goerge Morzbakh',
  'Heidar Basha',
  'Abo Rgela',
  'Hassan Amer',
  'Helmy Zamora',
  'Kamal Darweesh'
];
List<String> arabicpresidentnames = [
  'جورج مرزباخ',
  'حيدر باشا',
  'أبو رجيلة',
  'حسن عامر',
  'حلمي زمورا',
  'كمال درويش'
];

List<String> presidentperiod = [
  '1911 - 1915',
  '1923 = 1952',
  '1956 - 1961',
  '1962 - 1967\n1984 - 1988',
  '1967 - 1971\n1974 - 1984 ',
  '1996 - 2005'
];
List<String> legendsimages = [
  'aborgela.jpg',
  'ayman.jpg',
  'baheeg.jpg',
  'emanuel.jpg',
  'farouk.jpg',
  'fawzi.jpg',
  'gamal.jpg',
  'ghandor.jpg',
  'halim.jpg',
  'hamada.jpg',
  'hamed.jpg',
  'hazem.jpg',
  'hefny.jpg',
  'hossam.jpg',
  'kwarshy.jpg',
  'medhat.jpg',
  'mido.jpg',
  'shefo.jpg',
  'shehata.jpg',
  'shika.jpg',
  'taha.jpg',
  'tarek.jpg',
  'zaki.jpg',
  'zamora.jpg',
];
List<String> legendsnames = [
  'Abo Rgela',
  'Ayman Mansour',
  'Essam Baheeg',
  'Emanuel Amoneke',
  'Farouk Gaafar',
  'A.Fawzi',
  'Gamal Abdelhamid',
  'Khaled El Ghandor',
  'Abdelhalim Ali',
  'Hamada Emam',
  'Tarek Hamed',
  'Hazem Emam',
  'Ayman Hefny',
  'Hossam Hassan',
  'Kwarshy',
  'Medhat Abdelhady',
  'Mido',
  'M.Abdelshafy',
  'Hassan Shehata',
  'Shikabala',
  'Taha Basry',
  'Tarek El Sayed',
  'Amr Zaki',
  'Helmy Zamora',
];
List<String> arabiclegendsnames = [
  'أبو رجيلة',
  'أيمن منصور',
  'عصام بهيج',
  'إيمانويل أمونيكي',
  'فاروق جعفر',
  'أ.فوزي',
  'جمال عبد الحميد',
  'خالد الغندور',
  'عبد الحليم علي',
  'حمادة إمام',
  'طارق حامد',
  'حازم إمام',
  'أيمن حفني',
  'حسام حسن',
  'كوارشي',
  'مدحت عبد الهادي',
  'ميدو',
  'م.عبد الشافي',
  'حسن شحاتة',
  'شيكابالا',
  'طه بصري',
  'طارق السيد',
  'عمرو زكي',
  'حلمي زمورا',
];
