import 'package:new_project/Constants/Constants.dart';

List<Map<String, dynamic>> squadList = [
  {
    "No.": "1",
    "Pos.": "GK",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Awad",
    "Full Name": "Mohamed Awad",
    "PlayerImage": "${playersPath}awad.jpg",
    "Date of Birth": '1992/7/5',
    "Age": 31
  },
  {
    "No.": "2",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "H.Abdel Maguid",
    "Full Name": "Hossam Abdel Maguid",
    "PlayerImage": "${playersPath}hossam.jpg",
    "Date of Birth": '2001/4/29',
    "Age": 23
  },
  {
    "No.": "3",
    "Pos.": "DF",
    "Nation": "Palestine",
    "Shortnation": "PLE",
    "CountryImage": "${countriesPath}pa.png",
    "Player": "Y.Hamed",
    "Full Name": "Yaser Hamed",
    "PlayerImage": "${playersPath}yaser.jpg",
    "Date of Birth": '1997/12/8',
    "Age": 26
  },
  {
    "No.": "4",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "O.Gaber",
    "Full Name": "Omar Gaber",
    "PlayerImage": "${playersPath}gaber.jpg",
    "Date of Birth": '1992/1/29',
    "Age": 32
  },
  {
    "No.": "5",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.Hamdi",
    "Full Name": "Ahmed Hamdi",
    "PlayerImage": "${playersPath}hamdi.jpg",
    "Date of Birth": '1998/2/9',
    "Age": 26
  },
  {
    "No.": "6",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Zenary",
    "Full Name": "Mostafa El Zenary",
    "PlayerImage": "${playersPath}zenari.jpg",
    "Date of Birth": '1999/4/8',
    "Age": 25
  },
  {
    "No.": "7",
    "Pos.": "FW",
    "Nation": "Senegal",
    "Shortnation": "SEN",
    "CountryImage": "${countriesPath}sen.png",
    "Player": "I.Ndiaye",
    "Full Name": "Ibrahima Ndiaye",
    "PlayerImage": "${playersPath}nydai.jpg",
    "Date of Birth": '1998/7/5',
    "Age": 25
  },
  {
    "No.": "8",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "N.Donga",
    "Full Name": "Nabil Emad Donga",
    "PlayerImage": "${playersPath}donga.jpg",
    "Date of Birth": '1996/4/5',
    "Age": 28
  },
  {
    "No.": "9",
    "Pos.": "FW",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "N.Mansi",
    "Full Name": "Nasser Mansi",
    "PlayerImage": "${playersPath}nasermansi.jpg",
    "Date of Birth": '1996/12/31',
    "Age": 27
  },
  {
    "No.": "10",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "Shikabala",
    "Full Name": "Mahoumd Abdelrazek Shikabala",
    "PlayerImage": "${playersPath}shika.jpg",
    "Date of Birth": '1986/3/4',
    "Age": 38
  },
  {
    "No.": "11",
    "Pos.": "FW",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Shalaby",
    "Full Name": "Mostafa Shalaby",
    "PlayerImage": "${playersPath}shalaby.jpg",
    "Date of Birth": '1994/12/31',
    "Age": 29
  },
  {
    "No.": "12",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Roqa",
    "Full Name": "Mohamed Ashraf Roqa",
    "PlayerImage": "${playersPath}roqa.jpg",
    "Date of Birth": '1993/7/9',
    "Age": 30
  },
  {
    "No.": "13",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.Fotouh",
    "Full Name": "Ahmed Abou El Fotouh",
    "PlayerImage": "${playersPath}fatouh.jpg",
    "Date of Birth": '1998/3/21',
    "Age": 26
  },
  {
    "No.": "14",
    "Pos.": "FW",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "Y.Obama",
    "Full Name": "Youssef Ibrahim Obama",
    "PlayerImage": "${playersPath}obama.jpg",
    "Date of Birth": '1995/5/25',
    "Age": 29
  },
  {
    "No.": "15",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "Z.Kamal",
    "Full Name": "Ziad Kamal",
    "PlayerImage": "${playersPath}zyad.jpg",
    "Date of Birth": '2000/12/31',
    "Age": 23
  },
  {
    "No.": "16",
    "Pos.": "GK",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Sobhy",
    "Full Name": "Mohamed Sobhy",
    "PlayerImage": "${playersPath}sobhy.jpg",
    "Date of Birth": '1999/7/14',
    "Age": 24
  },
  {
    "No.": "17",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Shehata",
    "Full Name": "Mohamed Shehata",
    "PlayerImage": "${playersPath}shehata.jpg",
    "Date of Birth": '2000/12/31',
    "Age": 23
  },
  {
    "No.": "18",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "S.Nyemar",
    "Full Name": "Sayed Abdallah Nyemar",
    "PlayerImage": "${playersPath}neymar.jpg",
    "Date of Birth": '2000/1/11',
    "Age": 24
  },
  {
    "No.": "19",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.El Said",
    "Full Name": "Abdallah El Said",
    "PlayerImage": "${playersPath}elsaid.jpg",
    "Date of Birth": '1985/7/12',
    "Age": 38
  },
  {
    "No.": "20",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Alaa",
    "Full Name": "Mahmoud Alaa",
    "PlayerImage": "${playersPath}alaa.jpg",
    "Date of Birth": '1991/1/27',
    "Age": 33
  },
  {
    "No.": "21",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "S.Gaafar",
    "Full Name": "Seif Farouk Gaafar",
    "PlayerImage": "${playersPath}gafaar.jpg",
    "Date of Birth": '1999/12/4',
    "Age": 24
  },
  {
    "No.": "22",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "N.Maher",
    "Full Name": "Nasser Maher",
    "PlayerImage": "${playersPath}nasermaher.jpg",
    "Date of Birth": '1997/2/7',
    "Age": 27
  },
  {
    "No.": "23",
    "Pos.": "FW",
    "Nation": "Benin",
    "Shortnation": "BEN",
    "CountryImage": "${countriesPath}be.png",
    "Player": "S.Akinyoola",
    "Full Name": "Samson Akinyoola",
    "PlayerImage": "${playersPath}samson.jpg",
    "Date of Birth": '2000/3/2',
    "Age": 24
  },
  {
    "No.": "24",
    "Pos.": "DF",
    "Nation": "Tunisia",
    "Shortnation": "TUN",
    "CountryImage": "${countriesPath}tu.png",
    "Player": "H.AlMathlouthi",
    "Full Name": "Hamza AlMathlouthi",
    "PlayerImage": "${playersPath}hamza.jpg",
    "Date of Birth": '1992/7/24',
    "Age": 31
  },
  {
    "No.": "25",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.Zizo",
    "Full Name": "Ahmed Mostafa Zizo",
    "PlayerImage": "${playersPath}zizo.jpg",
    "Date of Birth": '1996/1/9',
    "Age": 28
  },
  {
    "No.": "26",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Yaser",
    "Full Name": "Mohab Yaser",
    "PlayerImage": "${playersPath}mohab.jpg",
    "Date of Birth": '1997/3/17',
    "Age": 27
  },
  {
    "No.": "27",
    "Pos.": "FW",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Atef",
    "Full Name": "Mohamed Atef",
    "PlayerImage": "${playersPath}atef.jpg",
    "Date of Birth": '2002/8/22',
    "Age": 21
  },
  {
    "No.": "28",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.El Wensh",
    "Full Name": "Mahmoud Hamdy El Wensh",
    "PlayerImage": "${playersPath}wensh.jpg",
    "Date of Birth": '1995/5/31',
    "Age": 29
  },
  {
    "No.": "29",
    "Pos.": "DF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Abdel Shafy",
    "Full Name": "Mohamed Abdel Shafy",
    "PlayerImage": "${playersPath}shefo.jpg",
    "Date of Birth": '1985/6/30',
    "Age": 38
  },
  {
    "No.": "30",
    "Pos.": "FW",
    "Nation": "Tunisia",
    "Shortnation": "TUN",
    "CountryImage": "${countriesPath}tu.png",
    "Player": "S.AlJaziri",
    "Full Name": "Seif-eldine AlJaziri",
    "PlayerImage": "${playersPath}giziri.jpg",
    "Date of Birth": '1993/2/11',
    "Age": 31
  },
  {
    "No.": "32",
    "Pos.": "GK",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "M.Alaaeldin",
    "Full Name": "Moaaz Alaaeldin",
    "PlayerImage": "${playersPath}moaz.jpg",
    "Date of Birth": '2003/5/16',
    "Age": 21
  },
  {
    "No.": "34",
    "Pos.": "GK",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.Nafad",
    "Full Name": "Abdul-Rahman Nafad",
    "PlayerImage": "${playersPath}nafad.jpg",
    "Date of Birth": '2004/3/31',
    "Age": 20
  },
  {
    "No.": "35",
    "Pos.": "MF",
    "Nation": "Egypt",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "A.Esho",
    "Full Name": "Ahmed Abdel Rahim",
    "PlayerImage": "${playersPath}esho.jpg",
    "Date of Birth": '2003/3/2',
    "Age": 21
  },
  {
    "No.": "40",
    "Pos.": "MF",
    "Nation": "Uganda",
    "Shortnation": "UGA",
    "CountryImage": "${countriesPath}ug.png",
    "Player": "T.Mutyaba",
    "Full Name": "Travis Mutyaba",
    "PlayerImage": "${playersPath}travis.jpg",
    "Date of Birth": '2005/8/6',
    "Age": 18
  },
];

List<Map<String, dynamic>> coach = [
  {
    "Pos.": "Coach",
    "Nation": "Portugal",
    "Shortnation": "Por",
    "Full Name": "Jose Gomez",
    "Coachpicture": "${ImagesPath}coach.jpg",
    "Date of Birth": '1970/8/27',
    "Age": 53
  },
];

List<Map<String, dynamic>> arabicsquadList = [
  {
    "No.": "1",
    "Pos.": "حارس مرمى",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "محمد عواد",
    "Full Name": "محمد عواد",
    "PlayerImage": "${playersPath}awad.jpg",
    "Date of Birth": '1992/7/5',
    "Age": 31
  },
  {
    "No.": "2",
    "Pos.": "مدافع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ح.عبد المجيد",
    "Full Name": "حسام عبد المجيد",
    "PlayerImage": "${playersPath}hossam.jpg",
    "Date of Birth": '2001/4/29',
    "Age": 23
  },
  {
    "No.": "3",
    "Pos.": "مدافع",
    "Nation": "فلسطين",
    "Shortnation": "PLE",
    "CountryImage": "${countriesPath}pa.png",
    "Player": "ياسر حمد",
    "Full Name": "ياسر حامد",
    "PlayerImage": "${playersPath}yaser.jpg",
    "Date of Birth": '1997/12/8',
    "Age": 26
  },
  {
    "No.": "4",
    "Pos.": "مدافع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "همر جابر",
    "Full Name": "عمر جابر",
    "PlayerImage": "${playersPath}gaber.jpg",
    "Date of Birth": '1992/1/29',
    "Age": 32
  },
  {
    "No.": "5",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "أحمد حمدي",
    "Full Name": "أحمد حمدي",
    "PlayerImage": "${playersPath}hamdi.jpg",
    "Date of Birth": '1998/2/9',
    "Age": 26
  },
  {
    "No.": "6",
    "Pos.": "مدافع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "م.زناري",
    "Full Name": "مصطفى الزناري",
    "PlayerImage": "${playersPath}zenari.jpg",
    "Date of Birth": '1999/4/8',
    "Age": 25
  },
  {
    "No.": "7",
    "Pos.": "مهاجم",
    "Nation": "السنغال",
    "Shortnation": "SEN",
    "CountryImage": "${countriesPath}sen.png",
    "Player": "إ.ندياي",
    "Full Name": "إبراهيم ندياي",
    "PlayerImage": "${playersPath}nydai.jpg",
    "Date of Birth": '1998/7/5',
    "Age": 25
  },
  {
    "No.": "8",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ن.دونجا",
    "Full Name": "نبيل عماد دونجا",
    "PlayerImage": "${playersPath}donga.jpg",
    "Date of Birth": '1996/4/5',
    "Age": 28
  },
  {
    "No.": "9",
    "Pos.": "مهاجم",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ناصر منسي",
    "Full Name": "ناصر منسي",
    "PlayerImage": "${playersPath}nasermansi.jpg",
    "Date of Birth": '1996/12/31',
    "Age": 27
  },
  {
    "No.": "10",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "شيكابالا",
    "Full Name": "محمود عبد الرازق شيكابالا",
    "PlayerImage": "${playersPath}shika.jpg",
    "Date of Birth": '1986/3/4',
    "Age": 38
  },
  {
    "No.": "11",
    "Pos.": "مهاجم",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "مصطفى شلبي",
    "Full Name": "مصطفى شلبي",
    "PlayerImage": "${playersPath}shalaby.jpg",
    "Date of Birth": '1994/12/31',
    "Age": 29
  },
  {
    "No.": "12",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "م.روقا",
    "Full Name": "محمد أشرف روقا",
    "PlayerImage": "${playersPath}roqa.jpg",
    "Date of Birth": '1993/7/9',
    "Age": 30
  },
  {
    "No.": "13",
    "Pos.": "مدافع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "أ.فتوح",
    "Full Name": "أحمد أبو الفتوح",
    "PlayerImage": "${playersPath}fatouh.jpg",
    "Date of Birth": '1998/3/21',
    "Age": 26
  },
  {
    "No.": "14",
    "Pos.": "مهاجم",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "يوسف أوباما",
    "Full Name": "يوسف إبراهيم أوباما",
    "PlayerImage": "${playersPath}obama.jpg",
    "Date of Birth": '1995/5/25',
    "Age": 29
  },
  {
    "No.": "15",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "زياد كمال",
    "Full Name": "زياد كمال",
    "PlayerImage": "${playersPath}zyad.jpg",
    "Date of Birth": '2000/12/31',
    "Age": 23
  },
  {
    "No.": "16",
    "Pos.": "حارس مرمى",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "محمد صبحي",
    "Full Name": "محمد صبحي",
    "PlayerImage": "${playersPath}sobhy.jpg",
    "Date of Birth": '1999/7/14',
    "Age": 24
  },
  {
    "No.": "17",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "محمد شحاتة",
    "Full Name": "محمد شحاتة",
    "PlayerImage": "${playersPath}shehata.jpg",
    "Date of Birth": '2000/12/31',
    "Age": 23
  },
  {
    "No.": "18",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "س.نيمار",
    "Full Name": "سيد عبد الله نيمار",
    "PlayerImage": "${playersPath}neymar.jpg",
    "Date of Birth": '2000/1/11',
    "Age": 24
  },
  {
    "No.": "19",
    "Pos.": "لاعب وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ع.السعيد",
    "Full Name": "عبد الله السعيد",
    "PlayerImage": "${playersPath}sayed.jpg",
    "Date of Birth": '1985/7/13',
    "Age": 39
  },
  {
    "No.": "20",
    "Pos.": "دفاع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "محمود علاء",
    "Full Name": "محمود علاء",
    "PlayerImage": "${playersPath}alaa.jpg",
    "Date of Birth": '1991/1/27',
    "Age": 33
  },
  {
    "No.": "21",
    "Pos.": "وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "سيف جعفر",
    "Full Name": "سيف فاروق جعفر",
    "PlayerImage": "${playersPath}gafaar.jpg",
    "Date of Birth": '1999/12/4',
    "Age": 24
  },
  {
    "No.": "22",
    "Pos.": "وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ناصر ماهر",
    "Full Name": "ناصر ماهر",
    "PlayerImage": "${playersPath}nasermaher.jpg",
    "Date of Birth": '1997/2/7',
    "Age": 27
  },
  {
    "No.": "23",
    "Pos.": "هجوم",
    "Nation": "بنين",
    "Shortnation": "BEN",
    "CountryImage": "${countriesPath}be.png",
    "Player": "س.أكينيولا",
    "Full Name": "سامسون أكينيولا",
    "PlayerImage": "${playersPath}samson.jpg",
    "Date of Birth": '2000/3/2',
    "Age": 24
  },
  {
    "No.": "24",
    "Pos.": "دفاع",
    "Nation": "تونس",
    "Shortnation": "TUN",
    "CountryImage": "${countriesPath}tu.png",
    "Player": "حمزةالمثلوثي",
    "Full Name": "حمزة المثلوثي",
    "PlayerImage": "${playersPath}hamza.jpg",
    "Date of Birth": '1992/7/24',
    "Age": 31
  },
  {
    "No.": "25",
    "Pos.": "وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "زيزو",
    "Full Name": "أحمد مصطفى زيزو",
    "PlayerImage": "${playersPath}zizo.jpg",
    "Date of Birth": '1996/1/9',
    "Age": 28
  },
  {
    "No.": "26",
    "Pos.": "وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "مهاب ياسر",
    "Full Name": "مهاب ياسر",
    "PlayerImage": "${playersPath}mohab.jpg",
    "Date of Birth": '1997/3/17',
    "Age": 27
  },
  {
    "No.": "27",
    "Pos.": "هجوم",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "محمدعاطف",
    "Full Name": "محمد عاطف",
    "PlayerImage": "${playersPath}atef.jpg",
    "Date of Birth": '2002/8/22',
    "Age": 21
  },
  {
    "No.": "28",
    "Pos.": "دفاع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "م.الونش",
    "Full Name": "محمود حمدي الونش",
    "PlayerImage": "${playersPath}wensh.jpg",
    "Date of Birth": '1995/5/31',
    "Age": 29
  },
  {
    "No.": "29",
    "Pos.": "دفاع",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "م.عبد الشافي",
    "Full Name": "محمد عبد الشافي",
    "PlayerImage": "${playersPath}shefo.jpg",
    "Date of Birth": '1985/6/30',
    "Age": 38
  },
  {
    "No.": "30",
    "Pos.": "هجوم",
    "Nation": "تونس",
    "Shortnation": "TUN",
    "CountryImage": "${countriesPath}tu.png",
    "Player": "سيف الجزيزي",
    "Full Name": "سيف الدين الجزيري",
    "PlayerImage": "${playersPath}giziri.jpg",
    "Date of Birth": '1993/2/11',
    "Age": 31
  },
  {
    "No.": "32",
    "Pos.": "حارس مرمى",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "م.علاء الدين",
    "Full Name": "معاذ علاء الدين",
    "PlayerImage": "${playersPath}moaz.jpg",
    "Date of Birth": '2003/5/16',
    "Age": 21
  },
  {
    "No.": "34",
    "Pos.": "حارس مرمى",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "ع.نفاد",
    "Full Name": "عبد الرحمن نفاد",
    "PlayerImage": "${playersPath}nafad.jpg",
    "Date of Birth": '2004/3/31',
    "Age": 20
  },
  {
    "No.": "35",
    "Pos.": "وسط",
    "Nation": "مصر",
    "Shortnation": "EGY",
    "CountryImage": "${countriesPath}eg.png",
    "Player": "أحمدإيشو",
    "Full Name": "أحمد عبد الرحيم",
    "PlayerImage": "${playersPath}esho.jpg",
    "Date of Birth": '2003/3/2',
    "Age": 21
  },
  {
    "No.": "40",
    "Pos.": "وسط",
    "Nation": "أوغندا",
    "Shortnation": "UGA",
    "CountryImage": "${countriesPath}ug.png",
    "Player": "ت.موتيابا",
    "Full Name": "ترافيس موتيابا",
    "PlayerImage": "${playersPath}travis.jpg",
    "Date of Birth": '2005/8/6',
    "Age": 18
  },
];

List<Map<String, dynamic>> arabiccoach = [
  {
    "Pos.": "مدير فني",
    "Nation": "البرتغال",
    "Shortnation": "Por",
    "Full Name": "خوسيه جوميز",
    "Coachpicture": "${ImagesPath}coach.jpg",
    "Date of Birth": '1970/8/27',
    "Age": 53
  },
];
