Map<String, dynamic> leagueData = {
  "teams": [
    {
      "position": 1,
      "name_ar": "بيراميدز",
      "name_en": "Pyramids FC",
      "played": 23,
      "won": 17,
      "drawn": 5,
      "lost": 1,
      "goal_difference": 11,
      "goals_for": 37,
      "goals_against": 14,
      "points": 56,
    },
    {
      "position": 2,
      "name_ar": "المصري البورسعيدي",
      "name_en": "El Masry Club",
      "played": 24,
      "won": 11,
      "drawn": 6,
      "lost": 7,
      "goal_difference": 10,
      "goals_for": 32,
      "goals_against": 31,
      "points": 39,
    },
    {
      "position": 3,
      "name_ar": "زد اف سي",
      "name_en": "ZED FC",
      "played": 23,
      "won": 9,
      "drawn": 10,
      "lost": 4,
      "goal_difference": 11,
      "goals_for": 30,
      "goals_against": 20,
      "points": 37,
    },
    {
      "position": 4,
      "name_ar": "إنبي",
      "name_en": "Enppi",
      "played": 24,
      "won": 10,
      "drawn": 6,
      "lost": 8,
      "goal_difference": 10,
      "goals_for": 29,
      "goals_against": 22,
      "points": 36,
    },
    {
      "position": 5,
      "name_ar": "الاتحاد السكندري",
      "name_en": "Al Ettehad ",
      "played": 25,
      "won": 9,
      "drawn": 9,
      "lost": 7,
      "goal_difference": 9,
      "goals_for": 28,
      "goals_against": 32,
      "points": 36,
    },
    {
      "position": 6,
      "name_ar": "مودرن فيوتشر",
      "name_en": "Modern Future FC",
      "played": 24,
      "won": 8,
      "drawn": 11,
      "lost": 5,
      "goal_difference": 10,
      "goals_for": 25,
      "goals_against": 19,
      "points": 35,
    },
    {
      "position": 7,
      "name_ar": "سموحة",
      "name_en": "Smouha",
      "played": 24,
      "won": 9,
      "drawn": 8,
      "lost": 7,
      "goal_difference": 10,
      "goals_for": 24,
      "goals_against": 23,
      "points": 35,
    },
    {
      "position": 8,
      "name_ar": "سيراميكا كليوباترا",
      "name_en": "Ceramica Cleopatra FC",
      "played": 23,
      "won": 9,
      "drawn": 7,
      "lost": 7,
      "goal_difference": 11,
      "goals_for": 37,
      "goals_against": 27,
      "points": 34,
    },
    {
      "position": 9,
      "name_ar": "الأهلي",
      "name_en": "Al Ahly",
      "played": 15,
      "won": 10,
      "drawn": 3,
      "lost": 2,
      "goal_difference": 19,
      "goals_for": 35,
      "goals_against": 16,
      "points": 33,
    },
    {
      "position": 10,
      "name_ar": "طلائع الجيش",
      "name_en": "Tala'ea El Gaish",
      "played": 23,
      "won": 8,
      "drawn": 9,
      "lost": 6,
      "goal_difference": 11,
      "goals_for": 19,
      "goals_against": 17,
      "points": 33,
    },
    {
      "position": 11,
      "name_ar": "الجونة",
      "name_en": "Al Gounah",
      "played": 25,
      "won": 7,
      "drawn": 9,
      "lost": 9,
      "goal_difference": 9,
      "goals_for": 26,
      "goals_against": 35,
      "points": 30,
    },
    {
      "position": 12,
      "name_ar": "الزمالك",
      "name_en": "El Zamalek",
      "played": 17,
      "won": 8,
      "drawn": 4,
      "lost": 5,
      "goal_difference": 17,
      "goals_for": 26,
      "goals_against": 16,
      "points": 28,
    },
    {
      "position": 13,
      "name_ar": "الإسماعيلي",
      "name_en": "Al Ismaily",
      "played": 25,
      "won": 6,
      "drawn": 9,
      "lost": 10,
      "goal_difference": 9,
      "goals_for": 25,
      "goals_against": 29,
      "points": 27,
    },
    {
      "position": 14,
      "name_ar": "البنك الأهلي",
      "name_en": "National Bank",
      "played": 25,
      "won": 6,
      "drawn": 5,
      "lost": 14,
      "goal_difference": 9,
      "goals_for": 34,
      "goals_against": 40,
      "points": 23,
    },
    {
      "position": 15,
      "name_ar": "بلدية المحلة",
      "name_en": "Baladiyet El Mahallah",
      "played": 24,
      "won": 6,
      "drawn": 4,
      "lost": 14,
      "goal_difference": 10,
      "goals_for": 24,
      "goals_against": 46,
      "points": 22,
    },
    {
      "position": 16,
      "name_ar": "فاركو",
      "name_en": "Pharco",
      "played": 23,
      "won": 4,
      "drawn": 9,
      "lost": 10,
      "goal_difference": 11,
      "goals_for": 22,
      "goals_against": 32,
      "points": 21,
    },
    {
      "position": 17,
      "name_ar": "المقاولون العرب",
      "name_en": "El Mokawloon El Arab",
      "played": 23,
      "won": 3,
      "drawn": 7,
      "lost": 13,
      "goal_difference": 11,
      "goals_for": 19,
      "goals_against": 36,
      "points": 16,
    },
    {
      "position": 18,
      "name_ar": "الداخلية",
      "name_en": "El Dakhleya",
      "played": 24,
      "won": 2,
      "drawn": 9,
      "lost": 13,
      "goal_difference": 10,
      "goals_for": 10,
      "goals_against": 27,
      "points": 15,
    }
  ]
};
